title: adamneale.uk
email: adam@adam-neale.co.uk
baseurl: ""
url: "https://adamneale.uk"

author: amneale
github_username: amneale
gitlab_username: amneale
linkedin_username: amneale
google_analytics: UA-19384655-2

# Build settings
markdown: kramdown
permalink: /:title/
collections:
  pages:
    output: true
    permalink: /:name/

sass:
  load_paths:
    - _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-avatar
  - jekyll-feed
